[package]
name = "tcp_flooder"
version = "0.1.0"
authors = ["Midas van Veen <midasvanveen.email@gmail.com>"]
license = "GNU"

[dependencies]
pnet = "0.25.0"
pnet_base = "0.25.0"
pnet_datalink = "0.25.0"
pnet_packet = "0.25.0"
pnet_transport = "0.25.0"
rand = "0.3.15"
colored = "2.0.0"
